# Build and test the DurationPicker package
name: CI

# Runs on pushes and pull requests targeting the default branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
# Allow one concurrent deployment
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # For list of all Xcode and iOS versions, see https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode
      - name: Select Xcode 15.1
        run: sudo xcode-select -s "/Applications/Xcode_15.1.app"
      - name: List available iOS simulators
        run: xcrun simctl list devices | grep -E "iPhone|iPad" | awk -F '[()]' '{print $1 ",", "iOS", $2}'
      - name: Run tests
        run: |
          xcodebuild test \
          -scheme DurationPicker \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro Max,OS=17.2' \
          -configuration Debug \
          || exit 1; \
